apiVersion: v1
kind: Service
metadata:
  name: whatsapp-saas-service
  namespace: whatsapp-saas
spec:
  selector:
    app: whatsapp-saas-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: whatsapp-saas
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432

---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: whatsapp-saas
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: whatsapp-saas
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017

---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
  namespace: whatsapp-saas
spec:
  selector:
    app: rabbitmq
  ports:
    - protocol: TCP
      port: 5672
      targetPort: 5672
    - protocol: TCP
      port: 15672
      targetPort: 15672

---
apiVersion: v1
kind: Service
metadata:
  name: chromadb-service
  namespace: whatsapp-saas
spec:
  selector:
    app: chromadb
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000